title: The non-sense mind about anything
author: SLacasse
email: lacasses@videotron.ca
description: > # this means to ignore newlines until "baseurl:"
  whatever comes to your mind random text words etcetera et tralala

# social links
twitter_username: lacasse22 # DO NOT include the @ character, or else the build will fail!
github_username:  lacasse22 # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage

theme: minima
